version: '3'
services:
  flextux:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: flextux
    ports:
      - 8080:8080
    env_file:
      - .env
    restart: always


    #environment:
    #  - DISCORD_TOKEN=${DISCORD_TOKEN}
    #  - DONO_ID=${DONO_ID}
    #  - PREFIX=${PREFIX}
    #  - TOP_GG_TOKEN=${TOP_GG_TOKEN}
    #  - TOP_GG_WEBHOOK=${TOP_GG_WEBHOOK}
    #  - MONGODB_URI=${MONGODB_URI}
    #  - WEBHOOK_SUGESTAO=${WEBHOOK_SUGESTAO}
